version: "3"
services:

    flaskapp:
        build: ./flaskapp
        expose:
            - "8000"
        env_file: .env
        environment:
            - TZ=PRC
        volumes:
            - ./flaskapp/app/static:/flaskapp/app/static
        command: ./wsgi.py

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./flaskapp/app/static:/nginx/static
